- name: "Copy salt config files to minion"
  template:
    src: "templates/{{ item.src }}"
    dest: "/etc/salt/{{ item.dst }}"
    mode: 0644
  with_items:
    - src: "salt-minion.conf.j2"
      dst: "minion"
  notify: "salt_restart"
