# Suse
- name: "SUSE - Check if salt repo is already added"
  stat:
    path: "/etc/zypp/repos.d/systemsmanagement_saltstack_products.repo"
  register: salt_repo

- name:
  zypper_repository:
    repo: "http://repo.saltstack.com/opensuse/{{ repo_folder }}/systemsmanagement:saltstack:products.repo"
    auto_import_keys: yes