- name: "UBUNTU - Install dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "python-apt"

- name: "UBUNTU - Add Salt APT key"
  apt_key:
    url: "https://repo.saltstack.com/apt/ubuntu/{{ ubuntu.version.number }}/amd64/latest/SALTSTACK-GPG-KEY.pub"
    state: present
    validate_certs: True

- name: "UBUNTU - Create Salt repo directory"
  template:
    src: "templates/ubuntu-saltstack.list.j2"
    dest: "/etc/apt/sources.list.d/saltstack.list"
    mode: 0644

